runner:
  total_steps: 15510 #30000  #181
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 141
  eval_step: 141
  save_step: 141
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: AdamW
  lr: 1.0e-4


downstream_expert:
  datarc:
    root: ./data/
    test_fold: fold1
    corpus: CREMA-D 
    p_or_s: Primary 
    pre_load: True
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 6


  modelrc:
    projector_dim: 256
    select: UtteranceLevel

    UtteranceLevel:
      pooling: MeanPooling

    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 80
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.4
